export default {
  map: {
    floorCount: 3,
    src: 'http://pjirfnf0s.bkt.clouddn.com/map_l.png',
    size: [1321, 1917],
  },
  floor: [
    {
      key: 1,
      name: '一楼',
      location: [-60, 190],
      catalog: ['总服务台', '新书', '文具', '生活', '休闲'],
      areas: [
        {
          key: 'a',
          color: '#fc9143',
          name: '总服务台',
          coordinate: [75, 740],
        },
        {
          key: 'b',
          color: '#fc9143',
          name: '新书平台',
          coordinate: [184, 668],
        },
        {
          key: 'c',
          color: '#1f6565',
          name: '生活休闲',
          coordinate: [389, 688],
        },
        {
          key: 'd',
          color: '#084f7d',
          name: '养生保健',
          coordinate: [427, 711],
        },
        {
          key: 'e',
          color: '#278d9b',
          name: '美妍西饼',
          coordinate: [206, 606],
        },
        {
          key: 'f',
          color: '#db185f',
          name: '视立美眼镜',
          coordinate: [312, 694],
        },
        {
          key: 'g',
          color: '#db185f',
          name: '晨光文具',
          coordinate: [282, 735],
        },
        {
          key: 'h',
          color: '#db185f',
          name: '浙里美新疆优品',
          coordinate: [320, 715],
        },
        {
          key: 'i',
          color: '#00c0cf',
          name: '日用品',
          coordinate: [400, 640],
        },
        {
          key: 'j',
          color: '#ef613a',
          name: '爱婴房',
          coordinate: [310, 805],
        },
      ],
    },
    {
      key: 2,
      name: '二楼',
      location: [-120, 160],
      catalog: ['文学', '科学', '社科', '数码', '沙龙', '展览'], 
      areas: [
        {
          key: 'a',
          color: '#fc9143',
          name: '中外文学',
          coordinate: [191, 498],
        },
        {
          key: 'b',
          color: '#ff3e3e',
          name: '古典文学',
          coordinate: [451, 510],
        },
        {
          key: 'c',
          color: '#7c3787',
          name: '自然科学',
          coordinate: [470, 445],
        },
        {
          key: 'd',
          color: '#db185f',
          name: '经济管理',
          coordinate: [404, 476],
        },
        {
          key: 'e',
          color: '#084f7d',
          name: '社科哲学',
          coordinate: [385, 430],
        },
        {
          key: 'f',
          color: '#1f6565',
          name: '艺法美术',
          coordinate: [418, 418],
        },
        {
          key: 'g',
          color: '#00c0cf',
          name: '政治法律',
          coordinate: [204, 356],
        },
        {
          key: 'h',
          color: '#ef613a',
          name: '学生数码',
          coordinate: [178, 404],
        },
        {
          key: 'i',
          color: '#278d9b',
          name: '本土作家',
          coordinate: [300, 383],
        },
      ],
    },
    {
      key: 3,
      name: '三楼',
      location: [-400, -130],
      catalog: ['书咖', '低幼', '文较', '多功能厅'], 
      areas: [
        {
          key: 'a',
          color: '#ff3e3e',
          name: '低幼读物',
          coordinate: [334, 257],
        },
        {
          key: 'b',
          color: '#7c3787',
          name: '儿童文学',
          coordinate: [158, 170],
        },
        {
          key: 'c',
          color: '#db185f',
          name: '小学文教',
          coordinate: [257, 207],
        },
        {
          key: 'd',
          color: '#00c0cf',
          name: '初中文教',
          coordinate: [377, 157],
        },
        {
          key: 'e',
          color: '#adb94b',
          name: '高中文教',
          coordinate: [385, 113],
        },
        {
          key: 'f',
          color: '#278d9b',
          name: '字典词典',
          coordinate: [490, 204],
        },
        {
          key: 'g',
          color: '#fc9143',
          name: '学习教育',
          coordinate: [231, 263],
        },
        {
          key: 'h',
          color: '#00b68a',
          name: '多功能厅',
          coordinate: [222, 96],
        },
        {
          key: 'i',
          color: '#278d9b',
          name: '护童学习桌',
          coordinate: [462, 256],
        },
        {
          key: 'j',
          color: '#084f7d',
          name: '时光故事书咖',
          coordinate: [538, 226],
        },
      ],
    },
  ],
}
