export default {
  map: {
    floorCount: 3,
    src: 'http://pjirfnf0s.bkt.clouddn.com/map_l.png',
    size: [1321, 1917],
  },
  floor: [
    {
      key: 1,
      name: '一楼',
      location: [397, 1638],
      catalog: ['总服务台', '新书', '文具', '生活', '休闲'],
      areas: [
        {
          key: 'a',
          color: '#fc9143',
          name: '总服务台',
          coordinate: [180, 1585],
        },
        {
          key: 'b',
          color: '#fc9143',
          name: '新书平台',
          coordinate: [395, 1440],
        },
        {
          key: 'c',
          color: '#1f6565',
          name: '生活休闲',
          coordinate: [848, 1470],
        },
        {
          key: 'd',
          color: '#084f7d',
          name: '养生保健',
          coordinate: [932, 1560],
        },
        {
          key: 'e',
          color: '#278d9b',
          name: '美妍西饼',
          coordinate: [430, 1311],
        },
        {
          key: 'f',
          color: '#db185f',
          name: '视立美眼镜',
          coordinate: [684, 1495],
        },
        {
          key: 'g',
          color: '#db185f',
          name: '晨光文具',
          coordinate: [615, 1590],
        },
        {
          key: 'h',
          color: '#db185f',
          name: '浙里美新疆优品',
          coordinate: [690, 1555],
        },
        {
          key: 'i',
          color: '#00c0cf',
          name: '日用品',
          coordinate: [842, 1387],
        },
        {
          key: 'j',
          color: '#ef613a',
          name: '爱婴房',
          coordinate: [670, 1720],
        },
      ],
    },
    {
      key: 2,
      name: '二楼',
      location: [626, 889],
      catalog: ['文学', '科学', '社科', '数码', '沙龙', '展览'], 
      areas: [
        {
          key: 'a',
          color: '#fc9143',
          name: '中外文学',
          coordinate: [420, 1096],
        },
        {
          key: 'b',
          color: '#ff3e3e',
          name: '古典文学',
          coordinate: [862, 1146],
        },
        {
          key: 'c',
          color: '#7c3787',
          name: '自然科学',
          coordinate: [1011, 970],
        },
        {
          key: 'd',
          color: '#db185f',
          name: '经济管理',
          coordinate: [862, 1055],
        },
        {
          key: 'e',
          color: '#084f7d',
          name: '社科哲学',
          coordinate: [826, 953],
        },
        {
          key: 'f',
          color: '#1f6565',
          name: '艺法美术',
          coordinate: [900, 900],
        },
        {
          key: 'g',
          color: '#00c0cf',
          name: '政治法律',
          coordinate: [456, 750],
        },
        {
          key: 'h',
          color: '#ef613a',
          name: '学生数码',
          coordinate: [388, 920],
        },
        {
          key: 'i',
          color: '#278d9b',
          name: '本土作家',
          coordinate: [666, 825],
        },
      ],
    },
    {
      key: 3,
      name: '三楼',
      location: [626, 290],
      catalog: ['书咖', '低幼', '文较', '多功能厅'], 
      areas: [
        {
          key: 'a',
          color: '#ff3e3e',
          name: '低幼读物',
          coordinate: [710, 550],
        },
        {
          key: 'b',
          color: '#7c3787',
          name: '儿童文学',
          coordinate: [340, 360],
        },
        {
          key: 'c',
          color: '#db185f',
          name: '小学文教',
          coordinate: [781, 454],
        },
        {
          key: 'd',
          color: '#00c0cf',
          name: '初中文教',
          coordinate: [820, 350],
        },
        {
          key: 'e',
          color: '#adb94b',
          name: '高中文教',
          coordinate: [850, 280],
        },
        {
          key: 'f',
          color: '#278d9b',
          name: '字典词典',
          coordinate: [1060, 420],
        },
        {
          key: 'g',
          color: '#fc9143',
          name: '学习教育',
          coordinate: [500, 580],
        },
        {
          key: 'h',
          color: '#00b68a',
          name: '多功能厅',
          coordinate: [483, 230],
        },
        {
          key: 'i',
          color: '#278d9b',
          name: '护童学习桌',
          coordinate: [990, 580],
        },
        {
          key: 'j',
          color: '#084f7d',
          name: '时光故事书咖',
          coordinate: [1165, 465],
        },
      ],
    },
  ],
}
